baseURL = "https://example.com"
languageCode = "eo"
defaultContentLanguage = "eo"
title = "Anubis"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Dmitry Kolosov"

[params]
   author = "Dmitry Kolosov"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = false

[languages.en]
  languageName = "English"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Archive"
  identifier = "archive"
  url = "/posts/"
  weight = 3

[languages.eo]
  languageName = "Esperanto"

[[languages.eo.menu.main]]
  identifier = "about"
  name = "Jen"
  url= "/about/"
  weight = 1

[[languages.eo.menu.main]]
  identifier = "tags"
  name = "Etikedoj"
  url = "/tags/"
  weight = 2

[[languages.eo.menu.main]]
  identifier = "archive"
  name = "Arkivo"
  url = "/posts/"
  weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true