baseURL = "https://strivenword.github.io/"
languageCode = "eo"
defaultContentLanguage = "eo"
title = "Resti"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Paul Lee"

[params]
   author = "Paul Lee"
   description = "Blogo pri restanto ĉi tie // A blog about staying here"
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "dark"
   readMore = false

[languages.en]
  languageName = "English"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Archive"
  identifier = "archive"
  url = "/posts/"
  weight = 3

[languages.eo]
  languageName = "Esperanto"

[[languages.eo.menu.main]]
  identifier = "about"
  name = "Jen"
  url= "/about/"
  weight = 1

[[languages.eo.menu.main]]
  identifier = "tags"
  name = "Etikedoj"
  url = "/tags/"
  weight = 2

[[languages.eo.menu.main]]
  identifier = "archive"
  name = "Arkivo"
  url = "/posts/"
  weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true